version: '3'

services:
  redis_db:
    image: redis
    ports:
      - 6379:6379
  app:
    build: .
    container_name: app
    depends_on:
      - redis_db
    ports:
      - 3000:3000
      - 5555:5555
    links:
      - redis_db
  